### PR TITLE
ci: fix action failures

### PR DESCRIPTION
**Pull request by stevenh**
Fix issues causing actions to report errors.

### CODE REVIEW

**Comment by nvuillam** [comment]
@stevenh I changed the settings of the repo, github action jobs should run without approval now :)

**Comment by nvuillam** [comment]
Don't worry about the auto commit failure, it's just because tou don't have the rights from a fork :)
And ignore codecov :)
But Windows & mac tests would be nice ^^

**Comment by stevenh** [comment]
> Don't worry about the auto commit failure, it's just because tou don't have the rights from a fork :) And ignore codecov :) But Windows & mac tests would be nice ^^

Yep, there seemed to be a way to do it but that requires contributors to make changes there end, so too high a barrier

I'm now looking to skip it when a fork is detected.

**Comment by stevenh** [comment]
Ok so node 12 is really old and the major version bumps didn't go quite to plan. Might want to consider dropping support for node 12 in the future.

**Comment by nvuillam** [comment]
@stevenh you can remove node 12 compat, good idea!

**Comment by stevenh** [comment]
> @stevenh you can remove node 12 compat, good idea!

Got it working for now, will do that later.

**Comment by stevenh** [comment]
Oh wow, wasn't expecting that to just pass, still had lots of debug in there.

I'll make sure I use a draft for work in progress

**Pull request merged**
