### PR TITLE
docs: fix required java version

### PR DESCRIPTION
**Pull request by ariyonaty**
## Fixes
Small change updating documentation specifying Java 17 as the primary version from the original range of versions 8 to 14.
Pulled the latest tool today and was met with the following despite having Java 11 installed:
```
$ npm-groovy-lint
Java jre or jdk 17 is required
Installing Java jre 17 in <path>
```

Hopefully this helps provide clarification to others as well.

### CODE REVIEW

**Comment by nvuillam** [comment]
Thanks @ariyonaty :)
Plz can you run `npm tun build` ?

**Comment by ariyonaty** [comment]
Alrighty.. clearly I'm doing something wrong. I'll stop kicking off checks until I get a follow up.
Unfortunately not familiar with node/npm, so this is a bit out of my element.

Tried: 
- Running `npm run build` standalone. Doesn't generate any diff.
- Running `npm install`, then `npm link`, followed by `npm run build`. Still no diff (aside from `package-lock.json`)
- In an attempt to mirror pipeline, `npm run dev:pre-commit` generates a diff in the form of updated `lib/java/CodeNarcServer.jar`, however latest build still shows failure.

Suggestions?

**Comment by nvuillam** [comment]
@stevenh can help us I think :)

**Comment by stevenh** [comment]
The change is in the generation of the server jar, have you followed the [guide I created for this problem](https://github.com/nvuillam/npm-groovy-lint/blob/main/CONTRIBUTING.md#troubleshooting)?

**Review by nvuillam — APPROVED** [review]
I updated your branch to make it pass, thanks for the PR :)

**Pull request merged**
