### PR TITLE
Add docker image with publishing

### PR DESCRIPTION
**Pull request by davegallant**
## Fixes

  - https://github.com/davegallant/docker-groovy-lint/issues/2

## Proposed Changes

  - Add Dockerfile
  - Add Docker Hub publishing via github actions

#### Notes

These changes would require:
- secrets added to this repository (`secrets.DOCKER_USERNAME` and `secrets.DOCKER_PASSWORD`)
- github actions (local and third party actions) enabled on the repository

As it stands now, the image would be published under: https://hub.docker.com/r/nvuillam

Docker publishing with github actions tested here: https://hub.docker.com/layers/davegallant/npm-groovy-lint-test/5.4.0/images/sha256-f5c98b40cb83955893da8b43c69bd9357947000da18cdb8690d78e00c2653cf8?context=explore

### CODE REVIEW

**Comment by nvuillam** [comment]
I see this PR is still draft, are you waiting from me just to add docker hub credentials, or do you need to make other updates ?

**Comment by davegallant** [comment]
> I see this PR is still draft, are you waiting from me just to add docker hub credentials, or do you need to make other updates ?

Credentials are needed. The rest should work as expected.

**Comment by nvuillam** [comment]
any tip about where I can put that ? I'm used to Jenkins & CircleCI but new to GH Actions :)

**Comment by nvuillam** [comment]
found it, nevermind ^^

**Comment by nvuillam** [comment]
Merged, + updated ... the image seems to be correctly built, I've not tested it, plz tell me if there is any issue :)

Many thanks for your contribution :) :)

**Pull request merged**
