### PR TITLE
fix: missing parse errors with --noserver

### LINKED ISSUE #323: --noserver does not honor --parse
Tracking differences between using `--noserver` or not (see #290), I stumbled on another difference: a file with a parse error will be seen as OK with `--noserver`, whereas it will fail without.

Fwiw, the reason for using `--noserver` is that I'm using npm-groovy-lint through Docker (on CI, but also locally), so starting a server for a one-shot analysis seemed unnecessary.
Given that `--noserver` is also used as a fallback for when the server codepath fails, I expect it to behave the same.

```shellsession
$ alias insidedocker
alias insidedocker='docker run --rm -it -u $(id -u):$(id -g) -v "$PWD:$PWD" -w "$PWD"'
$ insidedocker nvuillam/npm-groovy-lint:11.1.1 vars/utils.groovy
***REDACTED***/vars/utils.groovy
  17    error    Unexpected input: '***REDACTED***' @ line 17, column 1.  NglParseError


npm-groovy-lint results in 1 linted files:
┌─────────┬───────────┬─────────────┐
│ (index) │ Severity  │ Total found │
├─────────┼───────────┼─────────────┤
│    0    │  'Error'  │      1      │
│    1    │ 'Warning' │      0      │
│    2    │  'Info'   │      0      │
└─────────┴───────────┴─────────────┘
Failure: 1 error(s) have been found
 0 warning(s) have been found
 0 info(s) have been found
$ insidedocker nvuillam/npm-groovy-lint:11.1.1 --noserver dummy vars/utils.groovy dummy

npm-groovy-lint results in 1 linted files:
┌─────────┬───────────┬─────────────┐
│ (index) │ Severity  │ Total found │
├─────────┼───────────┼─────────────┤
│    0    │  'Error'  │      0      │
│    1    │ 'Warning' │      0      │
│    2    │  'Info'   │      0      │
└─────────┴───────────┴─────────────┘
```
(using version 11.1.1 here due to #319)

### PR DESCRIPTION
**Pull request by stevenh**
Refactor request processing so that the flow is the same with and without --noserver command line option which was preventing parse errors being reported when --noserver was specified.

Add duration in milliseconds to request logging so we easily monitor how long the server side requests are taking.

Explicitly handle 404 errors so we don't needlessly retry them with a slow direct request.

Use chaining to improve readability.

Fixes #323

### CODE REVIEW

**Comment by stevenh** [comment]
Mega-linter being shit and failing for spell using too many requests.

**Comment by stevenh** [comment]
@nvuillam in case you missed the notification for the review of this, cool if you just didn't have time yet.

**Review by nvuillam — APPROVED** [review]
Indeed i missed it , sometimes I check on my phone and tell myseld "i'll check later' then forget, you were right to ping me again :)

**Comment by nvuillam** [comment]
@stevenh do you want a new release right now or do you prefer to do it later yourself with new release management ?

**Comment by stevenh** [comment]
I'd say it can wait, not sure when I'll get chance to look at new release process but this would be a nice test case.

**Pull request merged**
