### PR TITLE
fix: server and test stability

### PR DESCRIPTION
**Pull request by stevenh**
Significant refactor of the server to improve stability  particularly to address hang on shutdown which was causing significant test instability.
    
Switch the logger for logback which adds the ability to do file and console logging and more making it easier to debug issues.

Increase max JVM version which was also contributing to server test instability.

Reduce ping timeout from 20 to 10 seconds now the server is more stable, adding in a retry if we get disconnected.

Enable server build clean up.

Rename dev:kill-server to server:kill to be consistent with other jobs.

To improve test stability:
* Move server tests to their own file as they have been the flaky ones, so its easier if they are grouped together.
* Move beforeEachTestCase into each test which needs it as beforeEach only gets run from the CLI meaning UI tests were broken.
* Remove lambdas so we can use skip
* Ensure temporary files are cleaned up.

### CODE REVIEW

**Comment by stevenh** [comment]
Sods law, running clean here and total failure in CI, think its the server tests, will look more.

**Comment by stevenh** [comment]
Nope looks like I used a feature of Java 11+ so all was exploding

**Comment by nvuillam** [comment]
@stevenh please let me know when you feel confident enough so I can release a new version then apply it to VsCode GroovyLint :)

If it's just one random test failure, you might consider disabling it on some contexts/platforms if you think it's really random and won't happen often on user configurations

**Comment by nvuillam** [comment]
I think we have to be pragmatic, as current version of npm-grovvy-lint fails almost everywhere, i prefer to release a version with a few bugs that we'll solve later, than a version not working at all like the current one ^^

Do I have your go ? :)

**Comment by stevenh** [comment]
Unfortunately, it seems to affect all tests randomly. I believe it's to do with the server starting and stopping while in the middle of the test run; which is why I've been working on ensure the server is doing as intended when kill is requested.

I've managed to get a reproducible scenario locally, but just haven't time to dig in this week.

**Comment by stevenh** [comment]
The current, main should be better than we had and it has the IPv4 fix in, which is one of the more important ones, so if you can test with a vscode build along side the current main and it works, then go for it.

**Comment by stevenh** [comment]
Making some good progress here, this is now a combo of the other PR's which have some dependencies when it comes to the tests.

I've had several clean runs on Java 17 both locally and here, but seeing errors on Java 21.

Will continue to investigate, so if you do want to hold off the release until next week, I may be able to crack it.

**Comment by stevenh** [comment]
I think I may have a break through, recommend holding fire.

**Comment by nvuillam** [comment]
Ok I hold fire :) ( and order a golden statut with your face for saving npm-groovy-lint :D )

**Comment by stevenh** [comment]
Ok it's not how I would want it, all in one PR, but this solves all but one of the issues I've seen.

Seems Java 8 is fails on reflection and Java 21 is not supported due to lack of ASM support.

I've marked the unstable tests as skip, but this should put us in a good place for a release.

**Review by nvuillam — APPROVED** [review]
Amazing ! ;)

**Pull request merged**
