### PR TITLE
Exclude UnnecessaryGetter, FactoryMethodName, MethodReturnTypeRequired, and GStringExpressionWithinString in recommended-jenkinsfile

### LINKED ISSUE #141: Consider excluding FactoryMethodName in recommended-jenkinsfile
For the same reason stated in https://github.com/nvuillam/npm-groovy-lint/pull/144.

I, for example, have a global function called `buildNpmProject`.

### LINKED ISSUE #142: Consider excluding MethodReturnTypeRequired in recommended-jenkinsfile
I'm not sure about this one, but since we already exclude the `NoDef` rule, would not make sense to exclude this one as well?

In my example I have:

```groovy
def buildNpmProject() {} // return type is void (there is no return)
```

### LINKED ISSUE #143: Ignore GStringExpressionWithinString when inside of sh step (Jenkinsfile)
I'm not sure if this is doable or not, but it would be great if this rule could be automatically ignored when checking for GStrings expressions within `sh` steps in Jenkinsfiles, since they actually mean environment variables accessible by the shell interpreter.

E.g.:

```groovy
sh '''
echo $SHELL
'''
```

### LINKED ISSUE #144: Consider excluding UnnecessaryGetter in recommended-jenkinsfile
Since we don't create classes for declarative pipelines, this rule does not make sense. Often, all we have is a function defined globally:

```groovy
boolean isTrue(boolean var) {
  return isTrue
}

pipeline {
  [...]
}
```

This rule would complain about the `isTrue` function name.

### PR DESCRIPTION
**Pull request by felipecrs**
Fixes #144, fixes #141, fixes #142, and fixes #143.

### CODE REVIEW

**Comment by nvuillam** [comment]
Thanks for your contribution :)
Please could you update CHANGELOG ?

**Comment by felipecrs** [comment]
@nvuillam can you please review again?

**Review by nvuillam — APPROVED** [review]
Good :)

**Comment by nvuillam** [comment]
Thanks a lot for your contribution :)

**Comment by nvuillam** [comment]
@felipecrs published 8.1.0 on NPM: https://www.npmjs.com/package/npm-groovy-lint
Not propagated to VsCodeGroovyLint yep

**Comment by felipecrs** [comment]
Thanks so much!

**Pull request merged**
