### PR TITLE
fix: parse error serialisation

### LINKED ISSUE #406: Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Document nesting depth (1001) exceeds the maximum allowed
Hey

I am facing an issue during linting of several groovy files I am using in a Jenkins Pipeline.
The log containing the exception can be seen here:
[Exception.log](https://github.com/user-attachments/files/16714533/Exception.log)

I am using the groovy linter now in several projects but only face this problem in one of them, it is a Jenkins Library.
What could be the problem causing this?

Thanks and best regards,
Fabian

### PR DESCRIPTION
**Pull request by stevenh**
Convert parse errors into strings manually to avoid JSON serialisation failure due to circular references.

Fixes #406

### CODE REVIEW

**Comment by stevenh** [comment]
Looks like this causes issues with tests, so needs more work

**Comment by nvuillam** [comment]
@stevenh I don't know what happens with codecov token (I generated a new one, but same strange result) , i'm ok to disable this part of the workflow :)

**Comment by echoix** [comment]
The step is also set with dry run true, so it won't upload anyways.

**Comment by echoix** [comment]
It seems that there are at least some users that works and fails randomly : https://github.com/codecov/codecov-action/issues/1548

**Pull request merged**
