### PR TITLE
fix: data race on stdout capture

### PR DESCRIPTION
**Pull request by stevenh**
Fix data race on stdout capture which was corrupting the responses for overlapping requests by using a capturing plugin.
    
Fix data race on threads read and write which could result in missed cancellations and re-enable cancellation processing.
    
Ensure that threads are always removed in the case of write response exception.
    
Switch to jackson to enable efficient JSON encoding and decoding including raw embedding of CodeNarc result to avoid unnecessary processing.
    
Split out HTTP filters to their own files.
    
Use typed variables instead of def per linter recommendation.
    
Add early test for missing base directory to avoid running linter unnecessarily.
    
Fix parse failures for files which contain classes that only non-zero argument constructors.
    
Add gzip compression to reduce size of network traffic to improve performance

### CODE REVIEW

**Comment by stevenh** [comment]
While this fixes the issues, I'm going to see if we can use a CodeNarc plugin to create a custom output writer that doesn't require locking as this will limit concurrency, which is not ideal.

**Comment by stevenh** [comment]
@nvuillam ready for review, it true fashion, should be split up but working as a whole, so...

**Review by nvuillam — APPROVED** [review]
Amazing :)

**Comment by nvuillam** [comment]
@stevenh released in https://github.com/nvuillam/npm-groovy-lint/releases/tag/v14.0.0 :)

**Pull request merged**
