### PR TITLE
fix: files not linting

### PR DESCRIPTION
**Pull request by stevenh**
Fix files specified on the command line not linting as expected due to the generated patterns not working as intended if relative path that contains a file and not a directory due to an issue with CodeNarc pattern processing.

Fix incompatible arguments passed to CodeNarc by:
* Using arrays internally to avoid issues with spaces in arguments being interpreted incorrectly.
* Stripping all quotes from string arguments as CodeNarc doesn't handle them correctly.
* Enable automatic argument quoting on Windows.

Fix command line -ext extensions not being processed correctly and matching too many files as it was missing the prefix.

Ensure readFile and writeFile calls produce a stack trace on failure due to: https://github.com/nodejs/node/issues/30944.

Fix file delete race condition and variable clean up due to missing await.

Fix use of includes instead of exclude parameters.

Also:
* Fixed Request failed logging
* Fix README.md typo
* Add additional useful debug logging
* Run dev:pre-commit to update CHANGELOG.md
* Add more cspell entries
* Add missing items to CodeNarcServer.groovy usage
* Re-enable tests which are now fixed
* Override axios for security patch

### CODE REVIEW

**Comment by stevenh** [comment]
@nvuillam this is draft as the server is built against an unreleased version for CodeNarc including [my PR to fix the pattern parsing](https://github.com/CodeNarc/CodeNarc/pull/753).

Also might be an idea to enforce all status checks passing on the repo before PR's can be merged as doc generation hadn't been run, which should have been flagged by the lint workflow.

**Comment by stevenh** [comment]
This is still blocked by https://github.com/CodeNarc/CodeNarc/issues/755

**Comment by nvuillam** [comment]
oops ^^

**Comment by stevenh** [comment]
This has highlighted some tests which are passing when they shouldn't. There's some pathing issues and looks like variance between how args are handled on Windows and Linux, in particular with files that have spaces in.

So more work to do on this one as well as the fix to CodeNarc.

**Comment by stevenh** [comment]
This is getting close now, CodeNarc has fix for excludes, just need to fix the variance on Windows with `--noserver`

**Comment by stevenh** [comment]
The Windows issues is down the argument handling set by [node-java-caller](https://github.com/nvuillam/node-java-caller).

PR to add option to allow that to be fixed is here: https://github.com/nvuillam/node-java-caller/pull/47, will update this PR with a full fix once that is merged and released.

**Comment by nvuillam** [comment]
@stevenh PR in node-java-caller merged , and new patch released ^^

**Comment by stevenh** [comment]
All tests now passing on all platforms. Fix for [CodeNarc Windows relative paths](https://github.com/CodeNarc/CodeNarc/pull/756) also merged.

As the ETA for a new release is Jan / Feb next year, I suggest we use CodeNarc built from master for now and update to a tagged version later.

**Comment by nvuillam** [comment]
@stevenh I agree, if you are confident with master version of CodeNarc ( I know it is maintained seriously), I can merge this PR and release a new major version ^^ )

Just give me your go :)

**Comment by stevenh** [comment]
Rebased to pickup new changes, should be good to go assuming tests all pass.

**Comment by nvuillam** [comment]
@stevenh please check your linkedin :)

**Review by nvuillam — APPROVED** [review]
That's great, as usual , many thanks @stevenh :)

**Pull request merged**
