### PR TITLE
Remove maximum java version constraint

### PR DESCRIPTION
**Pull request by nvuillam**
Fixes https://github.com/nvuillam/npm-groovy-lint/issues/257

### CODE REVIEW

**Comment by tylervz** [comment]
Hi @nvuillam I wanted to take a stab at getting tests passing on this Java 17 PR. I wanted to inspect what Java version is being used on the win & mac test cases, so I added the step:
```yaml
- name: Inspect Java version
  run: java --version
```
But that command fails:
```text
Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Error: Process completed with exit code 1.
```

https://github.com/tylervz/npm-groovy-lint/actions/runs/4994077727/jobs/8944119776#step:3:1

So now I'm a bit confused by how these test cases were ever passing. `npm ci && npm link` and `npm run test` are not magically installing Java, right?



P.S. some of the test steps failed when trying to download and use Node 12, so I upgraded them all to Node 16.

**Comment by kevin-dimichel** [comment]
@tylervz,

I'm not a java developer, but I noticed that the github actions use `runs-on: macos-latest`. And macos-latest now uses macOS 12 (see https://github.blog/changelog/2022-10-03-github-actions-jobs-running-on-macos-latest-are-now-running-on-macos-12/).  It also appears that these new macOS 12 agent images have three Javas installed (see https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#java).  You may need to use the fully path using the environment variable `$JAVA_HOME_17_X64`.

I was lead here because I'm not able to get npm-groovy-lint working on my m1 mac.

**Comment by tylervz** [comment]
Hi @kevin-dimichel , thanks for the tip! After trying to get it to work using the environment variable `$JAVA_HOME_17_X64`, I discovered that the recommended way to configure Java (even on the Windows and macOS runners) is to use the `actions/setup-java@v3` action as shown in the [Building and testing Java with Maven GitHub Actions documentation](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven#using-the-maven-starter-workflow).

Unfortunately, when I used `actions/setup-java@v3` to configure Java 17, the Windows and macOS test cases still failed just like all the others and I don't really understand the tests well enough to figure out which ones are failing and fix the problems so that the tests pass. https://github.com/tylervz/npm-groovy-lint/actions/runs/5403334378/jobs/9815985850

image

On the bright side, at least the Windows and macOS test cases completed running rather than timing out. Here's the end of the Windows and macOS "Run tests" step output, respectively:

```
2023-06-28T16:19:12.2017218Z   90) Miscellaneous
2023-06-28T16:19:12.2017449Z        (API:help) should show npm-groovy-lint version:
2023-06-28T16:19:12.2017576Z 
2023-06-28T16:19:12.2017684Z       AssertionError [ERR_ASSERTION]: Provides CodeNarc version
2023-06-28T16:19:12.2017867Z Returned outputString:
2023-06-28T16:19:12.2018071Z npm-groovy-lint version 11.1.1
2023-06-28T16:19:12.2018178Z 
2023-06-28T16:19:12.2018226Z Embeds:
2023-06-28T16:19:12.2018386Z CodeNarcServer: [-version]
2023-06-28T16:19:12.2018585Z - Groovy version 3.0.9 (superlite)
2023-06-28T16:19:12.2018772Z       + expected - actual
2023-06-28T16:19:12.2018865Z 
2023-06-28T16:19:12.2018938Z       -false
2023-06-28T16:19:12.2019050Z       +true
2023-06-28T16:19:12.2019171Z       
2023-06-28T16:19:12.2019340Z       at Context.<anonymous> (test\miscellaneous.test.js:257:9)
2023-06-28T16:19:12.2019591Z       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-06-28T16:19:12.2019749Z 
2023-06-28T16:19:12.2019806Z   91) Miscellaneous
2023-06-28T16:19:12.2019970Z        (API:Server) should kill running server:
2023-06-28T16:19:12.2020082Z 
2023-06-28T16:19:12.2020191Z       AssertionError [ERR_ASSERTION]: CodeNarcServer has been terminated
2023-06-28T16:19:12.2020411Z       + expected - actual
2023-06-28T16:19:12.2020503Z 
2023-06-28T16:19:12.2020575Z       -false
2023-06-28T16:19:12.2020696Z       +true
2023-06-28T16:19:12.2020801Z       
2023-06-28T16:19:12.2020970Z       at Context.<anonymous> (test\miscellaneous.test.js:274:9)
2023-06-28T16:19:12.2021100Z 
2023-06-28T16:19:12.2021105Z 
2023-06-28T16:19:12.2021110Z 
2023-06-28T16:19:12.2032966Z ##[error]Process completed with exit code 1.
```

```
  161) Miscellaneous
       (API:source) send anonymous usage statistics:
     TypeError: Cannot convert undefined or null to object
      at Function.keys (<anonymous>)
      at processOutput (lib/output.js:109:37)
      at NpmGroovyLint.postProcess (lib/groovy-lint.js:308:39)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async NpmGroovyLint.run (lib/groovy-lint.js:68:13)
      at async Context.<anonymous> (test/miscellaneous.test.js:159:24)

  162) Miscellaneous
       (API:source) should use a CodeNarc ruleset defined in groovylintrc.json:

      AssertionError [ERR_ASSERTION]: Linter status is 1 (0 returned)
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/miscellaneous.test.js:172:9)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

  163) Miscellaneous
       (API:help) should show npm-groovy-lint version:

      AssertionError [ERR_ASSERTION]: Provides CodeNarc version
Returned outputString:
npm-groovy-lint version 11.1.1

Embeds:
CodeNarcServer: [-version]
- Groovy version 3.0.9 (superlite)
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/miscellaneous.test.js:257:9)

  164) Miscellaneous
       (API:Server) should kill running server:

      AssertionError [ERR_ASSERTION]: CodeNarcServer has been terminated
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/miscellaneous.test.js:274:9)


Error: Process completed with exit code 164.
```

**Comment by kevin-dimichel** [comment]
@tylervz - Thanks for looking into it.  Maybe @nvuillam can take a peek at the failing tests. Hopefully your effort in your fork helps towards this PR.  : )

In the meantime, I got npm-groovy-lint working as a pre-commit hook after installing the pinned versions of java (zulu-8.70.0.23) and nodejs (20.3.1) using asdf.  I look forward to when this project support more modern java and node versions.

**Pull request closed without merging**
