### PR TITLE
Issue #338: Removing problematic console.log.

### PR DESCRIPTION
**Pull request by davidfmatheson**
## Fixes
Issue #338 

## Proposed Changes
Remove the console.log statement. There is already a debug statement with the same information.

### CODE REVIEW

**Comment by stevenh** [comment]
Thanks for this, looks like you just need to rebase to address the update check.

The Windows test run is flaky ATM as it seem to hang right at the end.

**Comment by nvuillam** [comment]
You probably also ned to run `npm run build` :)

**Review by nvuillam — APPROVED** [review]
Thanks for the PR :)

**Comment by nvuillam** [comment]
@davidfmatheson released in https://github.com/nvuillam/npm-groovy-lint/releases/tag/v13.0.2 , many thanks for your contribution :)

**Pull request merged**
